{"name": "Login Test with Different Credentials", "status": "passed", "attachments": [{"name": "Login Error Message", "source": "076d731f-9da0-4007-883b-3371e1a677f3-attachment.txt", "type": "text/plain"}, {"name": "Login Failure Screenshot", "source": "59d58c83-20e1-4c49-84c7-977227366673-attachment.png", "type": "image/png"}], "parameters": [{"name": "username", "value": "'wrong_user'"}, {"name": "password", "value": "'wrong_pass'"}], "start": 1744806182816, "stop": 1744806183503, "uuid": "1c81d56b-d279-4b3e-ade9-2399edaa3ba2", "historyId": "59392035fe46a49113c0f4d56ae34bf3", "testCaseId": "a707b9555172d26c5c1ec2d556e674f3", "fullName": "tests.test_login#test_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Kaustubh-Nitro5"}, {"name": "thread", "value": "16980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}